### ISSUE TITLE
Dim or Reduce contrast (feature request) 

### ISSUE THREAD

**Issue by mechengineermike** [tejashwikalptaru/ssd1306xled#4]
Overall this library is working great for me thanks! But there is a very limited set of commands, trying to figure out if there there is a way in sw to reduce the brightness to reduce the current draw.

**Comment by tejashwikalptaru** [comment]
Hi @mechengineermike nice idea to implement, I will try to implement this once I have some free time, meanwhile if you want, you can submit a PR with that.

**Comment by tejashwikalptaru** [comment]
Hi @mechengineermike the upcoming v1.0.0 https://github.com/tejashwikalptaru/ssd1306xled/pull/21 implements this functionality
