### ISSUE TITLE
Compatibility with ESP8266 Node MCU

### ISSUE THREAD

**Issue by cloter** [tejashwikalptaru/ssd1306xled#5]
I tried to use the library but it does not compile with ESP8266 (in Arduino IDE). I would like this feature, or at least an indication of what I need to modify in order to use it with ESP8266 Node MCU. Thanks!

**Comment by tejashwikalptaru** [comment]
You can use https://github.com/adafruit/Adafruit_SSD1306 with ESP8266, have not tested this library with anything else apart from ATTiny85. If you have some specific use case, do let me know, will try to help
